# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'instagramDownloadForm.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import datetime
import re
from PyQt5 import QtCore, QtGui, QtWidgets
from instagramFiles.instagramDownloader import InstagramDownloader
import os

class Ui_InstagramLoader(object):
    def setupUi(self, InstagramLoader):
        InstagramLoader.setObjectName("InstagramLoader")
        InstagramLoader.resize(800, 600)
        InstagramLoader.setMaximumSize(QtCore.QSize(800, 600))
        InstagramLoader.setStyleSheet("QMainWindow {background-color: #c13584;}")
        self.centralwidget = QtWidgets.QWidget(InstagramLoader)
        self.centralwidget.setObjectName("centralwidget")
        self.headerLabel = QtWidgets.QLabel(self.centralwidget)
        self.headerLabel.setGeometry(QtCore.QRect(260, 40, 311, 81))
        font = QtGui.QFont()
        font.setFamily("Rockwell Extra Bold")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(99)
        
        # header label
        self.headerLabel.setFont(font)
        self.headerLabel.setStyleSheet("QLabel {color: white;font-weight: 900;\n"
"};")
        self.headerLabel.setObjectName("headerLabel")
        
        # link text box
        self.linkTxtBox = QtWidgets.QLineEdit(self.centralwidget)
        self.linkTxtBox.setGeometry(QtCore.QRect(30, 130, 551, 41))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.linkTxtBox.setFont(font)
        self.linkTxtBox.setObjectName("linkTxtBox")
        
        # format group box
        self.formatGroupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.formatGroupBox.setGeometry(QtCore.QRect(40, 210, 171, 161))
        font = QtGui.QFont()
        font.setFamily("Rockwell Extra Bold")
        font.setBold(True)
        font.setWeight(99)
        self.formatGroupBox.setFont(font)
        self.formatGroupBox.setStyleSheet("color: white;font-weight: 900;\n"
"")
        self.formatGroupBox.setObjectName("formatGroupBox")
        self.formatGroupBox.setVisible(False)
        
        # mp4 radio button
        self.mp4Radio = QtWidgets.QRadioButton(self.formatGroupBox)
        self.mp4Radio.setGeometry(QtCore.QRect(20, 80, 141, 20))
        font = QtGui.QFont()
        font.setFamily("Rockwell Extra Bold")
        font.setBold(True)
        font.setWeight(99)
        self.mp4Radio.setFont(font)
        self.mp4Radio.setStyleSheet("color: white;font-weight: 900;")
        self.mp4Radio.setObjectName("mp4Radio")
        
        # mp3 radio button
        self.mp3Radio = QtWidgets.QRadioButton(self.formatGroupBox)
        self.mp3Radio.setGeometry(QtCore.QRect(20, 40, 141, 20))
        font = QtGui.QFont()
        font.setFamily("Rockwell Extra Bold")
        font.setBold(True)
        font.setWeight(99)
        self.mp3Radio.setFont(font)
        self.mp3Radio.setStyleSheet("color: white;font-weight: 900;")
        self.mp3Radio.setObjectName("mp3Radio")
        
        # downloads button
        self.downloadsButton = QtWidgets.QPushButton(self.centralwidget)
        self.downloadsButton.setGeometry(QtCore.QRect(620, 380, 121, 41))
        font = QtGui.QFont()
        font.setFamily("Rockwell Extra Bold")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.downloadsButton.setFont(font)
        self.downloadsButton.setStyleSheet("QPushButton {\n"
"                background-color: #FFFFFF; /* Beyaz arka plan */\n"
"                color: #c13584; /* Kırmızı yazı */\n"
"                font-size: 14px;\n"
"                font-weight: bold;\n"
"                border: 2px solid #c13584; /* Kırmızı kenar */\n"
"                border-radius: 8px; /* Hafif yuvarlak kenarlar */\n"
"                padding: 6px;\n"
"            }\n"
"            QPushButton:hover {\n"
"                background-color: #657786; /* Hover sırasında açık kırmızı */\n"
"                color: #FFFFFF; /* Yazı beyaz */\n"
"                border: 2px solid #383838;\n"
"            }\n"
"            QPushButton:pressed {\n"
"                background-color: #657786; /* Basılınca koyu kırmızı */\n"
"                color: #FFFFFF;\n"
"            }")
        self.downloadsButton.setObjectName("downloadsButton")
        self.searchButton = QtWidgets.QPushButton(self.centralwidget)
        self.searchButton.setGeometry(QtCore.QRect(590, 130, 201, 41))
        font = QtGui.QFont()
        font.setFamily("Rockwell Extra Bold")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.searchButton.setFont(font)
        self.searchButton.setStyleSheet("QPushButton {\n"
"                background-color: #FFFFFF; /* Beyaz arka plan */\n"
"                color: #c13584; /* Kırmızı yazı */\n"
"                font-size: 14px;\n"
"                font-weight: bold;\n"
"                border: 2px solid #c13584; /* Kırmızı kenar */\n"
"                border-radius: 8px; /* Hafif yuvarlak kenarlar */\n"
"                padding: 6px;\n"
"            }\n"
"            QPushButton:hover {\n"
"                background-color: #657786; /* Hover sırasında açık kırmızı */\n"
"                color: #FFFFFF; /* Yazı beyaz */\n"
"                border: 2px solid #383838;\n"
"            }\n"
"            QPushButton:pressed {\n"
"                background-color: #657786; /* Basılınca koyu kırmızı */\n"
"                color: #FFFFFF;\n"
"            }")
        self.searchButton.setObjectName("searchButton")
        self.qualityGroupbox = QtWidgets.QGroupBox(self.centralwidget)
        self.qualityGroupbox.setGeometry(QtCore.QRect(250, 210, 201, 221))
        font = QtGui.QFont()
        font.setFamily("Rockwell Extra Bold")
        font.setBold(True)
        font.setWeight(99)
        self.qualityGroupbox.setFont(font)
        self.qualityGroupbox.setStyleSheet("color: white;font-weight: 900;")
        self.qualityGroupbox.setObjectName("qualityGroupbox")
        self.qualityGroupbox.setVisible(False)
        
        self.quality480p = QtWidgets.QRadioButton(self.qualityGroupbox)
        self.quality480p.setGeometry(QtCore.QRect(40, 80, 141, 20))
        font = QtGui.QFont()
        font.setFamily("Rockwell Extra Bold")
        font.setBold(True)
        font.setWeight(99)
        self.quality480p.setFont(font)
        self.quality480p.setStyleSheet("color: white;font-weight: 900;")
        self.quality480p.setObjectName("quality480p")
        
        self.quality360p = QtWidgets.QRadioButton(self.qualityGroupbox)
        self.quality360p.setGeometry(QtCore.QRect(40, 40, 141, 20))
        font = QtGui.QFont()
        font.setFamily("Rockwell Extra Bold")
        font.setBold(True)
        font.setWeight(99)
        self.quality360p.setFont(font)
        self.quality360p.setStyleSheet("color: white;font-weight: 900;")
        self.quality360p.setObjectName("quality360p")
        
        self.quality720p = QtWidgets.QRadioButton(self.qualityGroupbox)
        self.quality720p.setGeometry(QtCore.QRect(40, 120, 141, 20))
        font = QtGui.QFont()
        font.setFamily("Rockwell Extra Bold")
        font.setBold(True)
        font.setWeight(99)
        self.quality720p.setFont(font)
        self.quality720p.setStyleSheet("color: white;font-weight: 900;")
        self.quality720p.setObjectName("quality720p")
        
        self.quality1080p = QtWidgets.QRadioButton(self.qualityGroupbox)
        self.quality1080p.setGeometry(QtCore.QRect(40, 160, 141, 20))
        font = QtGui.QFont()
        font.setFamily("Rockwell Extra Bold")
        font.setBold(True)
        font.setWeight(99)
        self.quality1080p.setFont(font)
        self.quality1080p.setStyleSheet("color: white;font-weight: 900;")
        self.quality1080p.setObjectName("quality1080p")
        
        InstagramLoader.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(InstagramLoader)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        InstagramLoader.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(InstagramLoader)
        self.statusbar.setObjectName("statusbar")
        InstagramLoader.setStatusBar(self.statusbar)

        self.retranslateUi(InstagramLoader)
        QtCore.QMetaObject.connectSlotsByName(InstagramLoader)
        
        self.instagram_downloader = InstagramDownloader()
        self.searchButton.clicked.connect(self.download_video)
        self.downloadsButton.clicked.connect(self.open_downloads_folder)
        
    def retranslateUi(self, InstagramLoader):
        _translate = QtCore.QCoreApplication.translate
        InstagramLoader.setWindowTitle(_translate("InstagramLoader", "Instagram Loader"))
        self.headerLabel.setText(_translate("InstagramLoader", "Download Instagram Videos"))
        self.formatGroupBox.setTitle(_translate("InstagramLoader", "Format"))
        self.mp4Radio.setText(_translate("InstagramLoader", "mp4"))
        self.mp3Radio.setText(_translate("InstagramLoader", "mp3"))
        self.downloadsButton.setText(_translate("InstagramLoader", "Downloads"))
        self.searchButton.setText(_translate("InstagramLoader", "Search and Download"))
        self.qualityGroupbox.setTitle(_translate("InstagramLoader", "Quality"))
        self.quality480p.setText(_translate("InstagramLoader", "480p"))
        self.quality360p.setText(_translate("InstagramLoader", "360p"))
        self.quality720p.setText(_translate("InstagramLoader", "720p"))
        self.quality1080p.setText(_translate("InstagramLoader", "1080p"))
    
    def open_downloads_folder(self):
        """
        Open the downloads folder
        """
        downloads_folder = self.instagram_downloader.download_folder
        if not os.path.exists(downloads_folder):
           os.makedirs(downloads_folder)
        
        os.startfile(downloads_folder)
    
    def download_video(self):
        """
        İndirme işlemini başlatır.
        """
        url = self.linkTxtBox.text().strip()
        if not url:
            QtWidgets.QMessageBox.warning(None, "Hata", "Lütfen bir link girin.")
            return

        # İndirme işlemi
        try:
           
           
           self.instagram_downloader.download(url)
           
           QtWidgets.QMessageBox.information(None, "Başarılı", f"Dosya indirildi.")
           self.linkTxtBox.clear()
        
        except Exception as e:
           QtWidgets.QMessageBox.warning(None, "Hata", f"İndirme sırasında hata oluştu: {e}")
           self.linkTxtBox.clear()
        

# if __name__ == "__main__":
#     import sys
#     app = QtWidgets.QApplication(sys.argv)
#     InstagramLoader = QtWidgets.QMainWindow()
#     ui = Ui_InstagramLoader()
#     ui.setupUi(InstagramLoader)
#     InstagramLoader.show()
#     sys.exit(app.exec_())
