# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainForm.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DownloadMate(object):
    def setupUi(self, DownloadMate):
        DownloadMate.setObjectName("DownloadMate")
        DownloadMate.resize(800, 500)
        DownloadMate.setMinimumSize(QtCore.QSize(800, 500))
        DownloadMate.setMaximumSize(QtCore.QSize(800, 500))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        DownloadMate.setFont(font)
        DownloadMate.setStatusTip("")
        DownloadMate.setLayoutDirection(QtCore.Qt.LeftToRight)
        DownloadMate.setStyleSheet("QWidget {\n"
"    background-color: #F5F5F5; /* Hafif gri (Örnek) */\n"
"}\n"
"")
        self.centralwidget = QtWidgets.QWidget(DownloadMate)
        self.centralwidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.centralwidget.setStyleSheet("QWidget {\n"
"    background-color: #D3D3D3; /* Hafif gri (Örnek) */\n"
"}\n"
"")
        self.centralwidget.setObjectName("centralwidget")
        self.youtubeDownloader = QtWidgets.QPushButton(self.centralwidget)
        self.youtubeDownloader.setGeometry(QtCore.QRect(230, 150, 350, 61))
        font = QtGui.QFont()
        font.setFamily("Segoe Script")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.youtubeDownloader.setFont(font)
        self.youtubeDownloader.setStyleSheet("QPushButton {\n"
"    background-color: #FF4C4C; /* Kırmızı buton rengi */\n"
"    color: white;             /* Yazı rengi */\n"
"    font-size: 16px;          /* Yazı boyutu */\n"
"    font-weight: bold;        /* Kalın yazı */\n"
"    border: none;             /* Çerçeve kaldırıldı */\n"
"    border-radius: 25px;      /* Tam yuvarlak köşeler */\n"
"    padding: 12px 24px;       /* İç boşluk */\n"
"    transition: all 0.3s ease; /* Geçiş efekti */\n"
"    text-transform: uppercase; /* Yazıyı büyük harf yapar */\n"
"    letter-spacing: 1px;      /* Yazı aralığı */\n"
"    box-shadow: 0px 5px 15px rgba(255, 76, 76, 0.4); /* Hafif gölge efekti */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #FF3333; /* Hover sırasında koyu kırmızı */\n"
"    box-shadow: 0px 8px 20px rgba(255, 76, 76, 0.6); /* Daha belirgin gölge */\n"
"    transform: translateY(-2px); /* Hafif yukarı hareket */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #CC0000; /* Tıklandığında daha koyu kırmızı */\n"
"    box-shadow: 0px 4px 10px rgba(255, 76, 76, 0.4); /* Daha küçük gölge */\n"
"    transform: scale(0.95);   /* Hafif küçültme efekti */\n"
"}\n"
"")
        self.youtubeDownloader.setObjectName("youtubeDownloader")
        self.twitterDownloader = QtWidgets.QPushButton(self.centralwidget)
        self.twitterDownloader.setGeometry(QtCore.QRect(230, 250, 350, 61))
        font = QtGui.QFont()
        font.setFamily("Segoe Script")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.twitterDownloader.setFont(font)
        self.twitterDownloader.setStyleSheet("QPushButton {\n"
"    background-color: #42ddf5; /* Mevcut mavi buton rengi */\n"
"    color: white;             /* Yazı rengi */\n"
"    font-size: 16px;          /* Yazı boyutu */\n"
"    font-weight: bold;        /* Kalın yazı */\n"
"    border: none;             /* Kenar çizgisi kaldırıldı */\n"
"    border-radius: 25px;      /* Tam yuvarlak köşeler */\n"
"    padding: 12px 24px;       /* İç boşluk */\n"
"    transition: all 0.3s ease; /* Geçiş efekti */\n"
"    text-transform: uppercase; /* Yazıyı büyük harf yapar */\n"
"    letter-spacing: 1px;      /* Yazı aralığı */\n"
"    box-shadow: 0px 5px 15px rgba(66, 221, 245, 0.4); /* Hafif gölge efekti */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #42c5f5; /* Hover sırasında daha koyu mavi */\n"
"    box-shadow: 0px 8px 20px rgba(66, 221, 245, 0.6); /* Daha belirgin gölge */\n"
"    transform: translateY(-2px); /* Hafif yukarı hareket */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #42c5f5; /* Tıklandığında daha koyu mavi */\n"
"    box-shadow: 0px 4px 10px rgba(66, 221, 245, 0.4); /* Daha küçük gölge */\n"
"    transform: scale(0.95);   /* Hafif küçültme efekti */\n"
"}\n"
"")
        self.twitterDownloader.setObjectName("twitterDownloader")
        self.instagramDownloader = QtWidgets.QPushButton(self.centralwidget)
        self.instagramDownloader.setGeometry(QtCore.QRect(230, 350, 350, 61))
        font = QtGui.QFont()
        font.setFamily("Segoe Script")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.instagramDownloader.setFont(font)
        self.instagramDownloader.setStyleSheet("QPushButton {\n"
"    background: qlineargradient(\n"
"        spread: pad,\n"
"        x1: 0,\n"
"        y1: 0,\n"
"        x2: 1,\n"
"        y2: 1,\n"
"        stop: 0 #FF512F, /* Turuncu */\n"
"        stop: 1 #DD2476 /* Mor */\n"
"    ); /* Gradient arka plan */\n"
"    color: white;             /* Yazı rengi */\n"
"    font-size: 16px;          /* Yazı boyutu */\n"
"    font-weight: bold;        /* Kalın yazı */\n"
"    border: none;             /* Çerçeve yok */\n"
"    border-radius: 25px;      /* Tam yuvarlak köşeler */\n"
"    padding: 12px 24px;       /* İç boşluk */\n"
"    transition: all 0.3s ease; /* Geçiş efekti */\n"
"    text-transform: uppercase; /* Yazıyı büyük harf yapar */\n"
"    letter-spacing: 1px;      /* Yazı aralığı */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    filter: brightness(1.1); /* Hover sırasında parlaklık efekti */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    filter: brightness(0.9); /* Tıklama sırasında koyulaşma efekti */\n"
"    transform: scale(0.95);  /* Hafif küçültme efekti */\n"
"}\n"
"")
        self.instagramDownloader.setObjectName("instagramDownloader")
        self.headerLabel = QtWidgets.QLabel(self.centralwidget)
        self.headerLabel.setGeometry(QtCore.QRect(130, 50, 511, 81))
        font = QtGui.QFont()
        font.setFamily("Segoe Script")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.headerLabel.setFont(font)
        self.headerLabel.setStyleSheet("QLabel {\n"
"    font-size: 24px;          /* Büyük yazı boyutu */\n"
"    font-weight: bold;        /* Kalın yazı */\n"
"    color: #333333;           /* Koyu gri renk */\n"
"    text-align: center;       /* Ortalanmış yazı */\n"
"    margin: 20px 0;           /* Üst ve alt boşluk */\n"
"    letter-spacing: 1px;      /* Hafif harf aralığı */\n"
"}\n"
"")
        self.headerLabel.setObjectName("headerLabel")
        DownloadMate.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(DownloadMate)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        DownloadMate.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(DownloadMate)
        self.statusbar.setObjectName("statusbar")
        DownloadMate.setStatusBar(self.statusbar)

        self.retranslateUi(DownloadMate)
        QtCore.QMetaObject.connectSlotsByName(DownloadMate)

    def retranslateUi(self, DownloadMate):
        _translate = QtCore.QCoreApplication.translate
        DownloadMate.setWindowTitle(_translate("DownloadMate", "DownloadMate"))
        self.youtubeDownloader.setText(_translate("DownloadMate", "Youtube Downloader"))
        self.twitterDownloader.setText(_translate("DownloadMate", "Twitter(X) Downloader"))
        self.instagramDownloader.setText(_translate("DownloadMate", "Instagram Downloader"))
        self.headerLabel.setText(_translate("DownloadMate", "DownloadMate Video Downloader"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    DownloadMate = QtWidgets.QMainWindow()
    ui = Ui_DownloadMate()
    ui.setupUi(DownloadMate)
    DownloadMate.show()
    sys.exit(app.exec_())
