//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace downloadmate.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("downloadmate.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ses.
        /// </summary>
        internal static string Audio {
            get {
                return ResourceManager.GetString("Audio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geri.
        /// </summary>
        internal static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cerez kaydedildi!.
        /// </summary>
        internal static string CookiesSaved {
            get {
                return ResourceManager.GetString("CookiesSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to instagram cerezi kaydedildi!.
        /// </summary>
        internal static string CookiesSavedInstagram {
            get {
                return ResourceManager.GetString("CookiesSavedInstagram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to indir.
        /// </summary>
        internal static string Download {
            get {
                return ResourceManager.GetString("Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to indirme tamamlandı:.
        /// </summary>
        internal static string DownloadCompleted {
            get {
                return ResourceManager.GetString("DownloadCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to indirme klasörü bulunamadı..
        /// </summary>
        internal static string DownloadFolderMissing {
            get {
                return ResourceManager.GetString("DownloadFolderMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hata olustu:.
        /// </summary>
        internal static string ErrorOccurred {
            get {
                return ResourceManager.GetString("ErrorOccurred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giriş URL&apos;si:.
        /// </summary>
        internal static string InputUrl {
            get {
                return ResourceManager.GetString("InputUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instagram.
        /// </summary>
        internal static string InstagramLogin {
            get {
                return ResourceManager.GetString("InstagramLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DownloadMate.
        /// </summary>
        internal static string Main {
            get {
                return ResourceManager.GetString("Main", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İndirilenler.
        /// </summary>
        internal static string OpenDownloads {
            get {
                return ResourceManager.GetString("OpenDownloads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dosyayı Ac.
        /// </summary>
        internal static string OpenFile {
            get {
                return ResourceManager.GetString("OpenFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adlandır:.
        /// </summary>
        internal static string RenameFile {
            get {
                return ResourceManager.GetString("RenameFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dili Seç:.
        /// </summary>
        internal static string SelectLanguage {
            get {
                return ResourceManager.GetString("SelectLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seçiniz.
        /// </summary>
        internal static string SelectOption {
            get {
                return ResourceManager.GetString("SelectOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temayı Seç:.
        /// </summary>
        internal static string SelectTheme {
            get {
                return ResourceManager.GetString("SelectTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ayarlar.
        /// </summary>
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sosyal Medya Girisi:.
        /// </summary>
        internal static string SocialLogin {
            get {
                return ResourceManager.GetString("SocialLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sosyal Medya Girisi.
        /// </summary>
        internal static string SocialMediaLogin {
            get {
                return ResourceManager.GetString("SocialMediaLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DownloadMate.
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tür:.
        /// </summary>
        internal static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to video.
        /// </summary>
        internal static string Video {
            get {
                return ResourceManager.GetString("Video", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Youtube.
        /// </summary>
        internal static string YoutubeLogin {
            get {
                return ResourceManager.GetString("YoutubeLogin", resourceCulture);
            }
        }
    }
}
