# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'youtubeDownloadForm.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setMinimumSize(QtCore.QSize(800, 600))
        MainWindow.setMaximumSize(QtCore.QSize(800, 600))
        font = QtGui.QFont()
        font.setFamily("Segoe Script")
        MainWindow.setFont(font)
        MainWindow.setStyleSheet("QMainWindow {\n"
"                background-color: #FFCCCC; /* Hafif kırmızı arka plan */\n"
"            }")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.headerLabel = QtWidgets.QLabel(self.centralwidget)
        self.headerLabel.setGeometry(QtCore.QRect(270, 70, 271, 81))
        font = QtGui.QFont()
        font.setFamily("Segoe Script")
        font.setPointSize(10)
        self.headerLabel.setFont(font)
        self.headerLabel.setObjectName("headerLabel")
        self.linkTxtBox = QtWidgets.QLineEdit(self.centralwidget)
        self.linkTxtBox.setGeometry(QtCore.QRect(50, 150, 551, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.linkTxtBox.setFont(font)
        self.linkTxtBox.setObjectName("linkTxtBox")
        self.formatGroupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.formatGroupBox.setGeometry(QtCore.QRect(40, 230, 171, 161))
        font = QtGui.QFont()
        font.setFamily("Segoe Script")
        self.formatGroupBox.setFont(font)
        self.formatGroupBox.setObjectName("formatGroupBox")
        self.mp4Radio = QtWidgets.QRadioButton(self.formatGroupBox)
        self.mp4Radio.setGeometry(QtCore.QRect(20, 80, 141, 20))
        font = QtGui.QFont()
        font.setFamily("Segoe Script")
        self.mp4Radio.setFont(font)
        self.mp4Radio.setObjectName("mp4Radio")
        self.mp3Radio = QtWidgets.QRadioButton(self.formatGroupBox)
        self.mp3Radio.setGeometry(QtCore.QRect(20, 40, 141, 20))
        font = QtGui.QFont()
        font.setFamily("Segoe Script")
        self.mp3Radio.setFont(font)
        self.mp3Radio.setObjectName("mp3Radio")
        self.searchButton = QtWidgets.QPushButton(self.centralwidget)
        self.searchButton.setGeometry(QtCore.QRect(630, 150, 121, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe Script")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.searchButton.setFont(font)
        self.searchButton.setStyleSheet("QPushButton {\n"
"                background-color: #FFFFFF; /* Beyaz arka plan */\n"
"                color: #FF0000; /* Kırmızı yazı */\n"
"                font-size: 14px;\n"
"                font-weight: bold;\n"
"                border: 2px solid #FF0000; /* Kırmızı kenar */\n"
"                border-radius: 8px; /* Hafif yuvarlak kenarlar */\n"
"                padding: 6px;\n"
"            }\n"
"            QPushButton:hover {\n"
"                background-color: #FF4C4C; /* Hover sırasında açık kırmızı */\n"
"                color: #FFFFFF; /* Yazı beyaz */\n"
"                border: 2px solid #FF0000;\n"
"            }\n"
"            QPushButton:pressed {\n"
"                background-color: #CC0000; /* Basılınca koyu kırmızı */\n"
"                color: #FFFFFF;\n"
"            }")
        self.searchButton.setObjectName("searchButton")
        self.qualityGroupbox = QtWidgets.QGroupBox(self.centralwidget)
        self.qualityGroupbox.setGeometry(QtCore.QRect(250, 230, 201, 221))
        font = QtGui.QFont()
        font.setFamily("Segoe Script")
        self.qualityGroupbox.setFont(font)
        self.qualityGroupbox.setObjectName("qualityGroupbox")
        self.mp4Radio_4 = QtWidgets.QRadioButton(self.qualityGroupbox)
        self.mp4Radio_4.setGeometry(QtCore.QRect(40, 80, 141, 20))
        font = QtGui.QFont()
        font.setFamily("Segoe Script")
        self.mp4Radio_4.setFont(font)
        self.mp4Radio_4.setObjectName("mp4Radio_4")
        self.mp3Radio_4 = QtWidgets.QRadioButton(self.qualityGroupbox)
        self.mp3Radio_4.setGeometry(QtCore.QRect(40, 40, 141, 20))
        font = QtGui.QFont()
        font.setFamily("Segoe Script")
        self.mp3Radio_4.setFont(font)
        self.mp3Radio_4.setObjectName("mp3Radio_4")
        self.mp4Radio_5 = QtWidgets.QRadioButton(self.qualityGroupbox)
        self.mp4Radio_5.setGeometry(QtCore.QRect(40, 120, 141, 20))
        font = QtGui.QFont()
        font.setFamily("Segoe Script")
        self.mp4Radio_5.setFont(font)
        self.mp4Radio_5.setObjectName("mp4Radio_5")
        self.mp4Radio_6 = QtWidgets.QRadioButton(self.qualityGroupbox)
        self.mp4Radio_6.setGeometry(QtCore.QRect(40, 160, 141, 20))
        font = QtGui.QFont()
        font.setFamily("Segoe Script")
        self.mp4Radio_6.setFont(font)
        self.mp4Radio_6.setObjectName("mp4Radio_6")
        self.downloadsLabel = QtWidgets.QPushButton(self.centralwidget)
        self.downloadsLabel.setGeometry(QtCore.QRect(630, 400, 121, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe Script")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.downloadsLabel.setFont(font)
        self.downloadsLabel.setStyleSheet("QPushButton {\n"
"                background-color: #FFFFFF; /* Beyaz arka plan */\n"
"                color: #FF0000; /* Kırmızı yazı */\n"
"                font-size: 14px;\n"
"                font-weight: bold;\n"
"                border: 2px solid #FF0000; /* Kırmızı kenar */\n"
"                border-radius: 8px; /* Hafif yuvarlak kenarlar */\n"
"                padding: 6px;\n"
"            }\n"
"            QPushButton:hover {\n"
"                background-color: #FF4C4C; /* Hover sırasında açık kırmızı */\n"
"                color: #FFFFFF; /* Yazı beyaz */\n"
"                border: 2px solid #FF0000;\n"
"            }\n"
"            QPushButton:pressed {\n"
"                background-color: #CC0000; /* Basılınca koyu kırmızı */\n"
"                color: #FFFFFF;\n"
"            }")
        self.downloadsLabel.setObjectName("downloadsLabel")
        self.resultLabel = QtWidgets.QLabel(self.centralwidget)
        self.resultLabel.setGeometry(QtCore.QRect(580, 240, 151, 81))
        font = QtGui.QFont()
        font.setFamily("Segoe Script")
        self.resultLabel.setFont(font)
        self.resultLabel.setText("")
        self.resultLabel.setObjectName("resultLabel")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.headerLabel.setText(_translate("MainWindow", "Download Youtube Videos"))
        self.formatGroupBox.setTitle(_translate("MainWindow", "Format"))
        self.mp4Radio.setText(_translate("MainWindow", "mp4"))
        self.mp3Radio.setText(_translate("MainWindow", "mp3"))
        self.searchButton.setText(_translate("MainWindow", "Search Link"))
        self.qualityGroupbox.setTitle(_translate("MainWindow", "Quality"))
        self.mp4Radio_4.setText(_translate("MainWindow", "480p"))
        self.mp3Radio_4.setText(_translate("MainWindow", "360p"))
        self.mp4Radio_5.setText(_translate("MainWindow", "720p"))
        self.mp4Radio_6.setText(_translate("MainWindow", "1080p"))
        self.downloadsLabel.setText(_translate("MainWindow", "Downloads"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
