version: '3.8'

services:
  fastapi:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8010:8010"
    volumes:
      - .:/app  # İstersen production'da bunu kaldırabilirsin
    environment:
      - PYTHONUNBUFFERED=1
    restart: always
