version: '3.8'

services:
  fastapi:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8010:8010"
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
    restart: always 
